title:            "Ryoko and Ugo's wedding"
description:      "August 22nd 2014"
#logo:             site-logo.png
disqus_shortname: 
search:           true
encoding:         UTF-8
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://www.ryokoandugo.com

# Owner/author information
owner:
  name:           Ugo Bataillard
  avatar:         bio-photo.jpg
  email:          public_at_ugo.me
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics: UA-49012373-1
google_verify:      
google_api_key: AIzaSyDBdzW2v4W7OHc3ZbfBHykznD6X52u8M9M
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Venue
    url: /venue/
  - title: Gallery
    url: /gallery/
  - title: Accomodation
    url: /accomodation/
  - title: RSVP
    url: /rsvp/
# - title: Articles
#    url: /articles/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Tokyo
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Internationalization
venue:
  en:
    schedule: "The schedule"
    ceremony: "The ceremony"
    ceremony_desc: "The ceremony will be held at the \"Salle des mariages\" of La Seyne-sur-mer at 15:00"
    reception: "The reception"
    reception_desc: "The reception will be held at [**\"La Magnanerie de Saint Isidore\"**](http://lamagnanerie.eu/) from 18:00"
  fr:
    schedule: "Le programme"
    ceremony: "La ceremonie"
    ceremony_desc: "La ceremonie aura lieu a la \"Salle des mariages\" de La Seyne-sur-mer a 15:00"
    reception: "La reception"
    reception_desc: "La reception aura lieu a [**\"La Magnanerie de Saint Isidore\"**](http://lamagnanerie.eu/) a partir de 18:00"

rsvp:
  en:
    name:           "Full name"
    email:          "Email"
    coming_q:       "Coming?"
    coming:         "Coming"
    not_coming:     "Not coming"
    guest_number:   "Number of guests attending including you"
    address:        "Address"
    tel:            "Tel"
  fr:
    name:           "Nom complet"
    email:          "Email"
    coming_q:        "Pourra venir ?"
    coming:         "Oui"
    not_coming:     "Non"
    guest_number:   "Nombre de personne vous inclus"
    address:        "Adresse"
    tel:            "Tel"

